bot:
  token: 7648328078:AAGezSXzBjeKUA322aLCSv2BYcoSFvbdxMI

tg:
  api_id: 26378134
  api_hash: f081f6b475a04a811a7bc00ebdd29689

redis:
  port: 6380
  host: localhost
  cache_prefix: bot:cache

http:
  port: 3000

db:
  port: 5432
  host: localhost
  username: postgres
  password: postgres
  dbname: postgres
  sslmode: disable

kafka:
  producer_topics:
    new_message: new-message